// MASTER-FRAMEWORKD-JS/aprendiendo-vue/src/components/PeliculaComponent.vue
<template>
    <article class="article-item" >
        <div class="images-wrap">
            <img :src="pelicula.image" :alt="pelicula.title" />
        </div>

        <h2>{{pelicula.title}}</h2>
        <span class="date" :class="{
            yeargreen:pelicula.year >= 2020,
            yearred:pelicula.year <= 2020
        }">
            {{pelicula.year}}
        </span>
        <a href="#">Leer mas</a>

        <input type="button" value="Marcar como favorita"
            v-on:click="pasarFavoritaAlPadre(pelicula)"
        />

        <div class="clearfix"></div>
    </article>
</template>

<script>
export default {
    name: 'PeliculaComponent',
    props: ['pelicula'],
    methods:{
        pasarFavoritaAlPadre(pelicula){
            this.$emit('favorita',pelicula);
        }
    }
}
</script>

// MASTER-FRAMEWORKD-JS/AprendiendoAngular/src/app/components/pelicula/pelicula.component.ts
import { Component,OnInit,Input, Output, EventEmitter } from '@angular/core';
import { Pelicula } from '../../models/pelicula';

@Component({
  selector: 'app-pelicula',
  standalone: false,
  templateUrl: './pelicula.component.html',
  styleUrl: './pelicula.component.css'
})
export class PeliculaComponent implements OnInit {

  @Input() pelicula : Pelicula = {'image':'','year':0,'title':''};
  @Output() MarcarFavorita = new EventEmitter(); 

  constructor(){
  };

  ngOnInit(): void {
  };

  seleccionar(event: any,pelicula:any){
    console.log(pelicula);
    this.MarcarFavorita.emit({
      pelicula:pelicula
    })
  };

}

<article class="article-item">
    <div class="images-wrap">
        <img src="{{pelicula.image}}" alt="{{pelicula.title}}" />
    </div>

    <h2>{{pelicula.title}}</h2>
    <span class="date">
        Hace 5 minutos
    </span>

    <span class="year" [ngClass]="{
                            'year-green': pelicula.year > 2019,
                            'year-red': pelicula.year < 2019
                    }">
        {{pelicula.year}}
    </span>

    <a href="#">Leer mas</a>

    <button (click)="seleccionar($event, pelicula)">
        Seleccionar como favorita
    </button>
    <div class="clearfix"></div>
</article>
