// MASTER-FRAMEWORKD-JS/aprendiendo-vue/src/components/FormularioComponent.vue
<template>
    <div class="general">
        <div class="center">
            <section id="content">
                <h1 class="subheader">Formulario</h1>
                <form class="mid-form" @submit.prevent="mostrarUsuario()">
                    <div class="form-group">
                        <label for="nombre">Nombre</label>
                        <input type="text" name="nombre" v-model="user.nombre" />
                        <div class="input-errors" v-if="submitted && v$.user.nombre.required.$invalid">
                            Este campo es requerido
                        </div>
                        <div class="input-errors" v-if="submitted && v$.user.nombre.minLength.$invalid">
                            Este campo debe tener mas caracteres
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="apellidos">Apellidos</label>
                        <input type="text" name="apellidos" v-model="user.apellidos"/>
                        <div class="input-errors" v-if="submitted && v$.user.apellidos.required.$invalid">
                            Este campo es requerido
                        </div>
                        <div class="input-errors" v-if="submitted && v$.user.apellidos.minLength.$invalid">
                            Este campo debe tener mas caracteres
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="bio">Biografia</label>
                        <textarea name="bio" v-model="user.bio"></textarea>
                        <div class="input-errors" v-if="submitted && v$.user.bio.required.$invalid">
                            Este campo es requerido
                        </div>
                        <div class="input-errors" v-if="submitted && v$.user.bio.minLength.$invalid">
                            Este campo debe tener mas caracteres
                        </div>
                    </div>
                    <div class="form-group radibuttons">
                        <input type="radio" name="genero" value="hombre" v-model="user.genero"/> Hombre
                        <input type="radio" name="genero" value="mujer" v-model="user.genero"/> Mujer
                        <input type="radio" name="genero" value="otro" v-model="user.genero"/> Otro
                    </div>
                    <div class="clearfix"></div>
                    <input type="submit" value="Enviar" class="btn btn-success"/>
                </form>
            </section>
        </div>
        <SiderbarComponent></SiderbarComponent>
        <div class="clearfix"></div>
    </div> 
</template>

<script>
import { useVuelidate } from '@vuelidate/core'
import { required, minLength } from '@vuelidate/validators'
import SiderbarComponent from './SiderbarComponent.vue';

export default {
    name: 'FormularioComponent',
    setup () {
        return { v$: useVuelidate() }
    },
    components:{
        SiderbarComponent
    },
    validations:{
        user: {
            nombre:{
                required,
                minLength: minLength(2)
            },
            apellidos:{
                required,
                minLength: minLength(2)
            },
            bio:{
                required,
                minLength: minLength(10)
            }
        }
    },
    data(){
        return {
            submitted:false,
            user: {
                nombre: '',
                apellidos: '',
                bio: '',
                genero: ''
            }
        }
    },
    methods:{
        mostrarUsuario(){
            console.log(this.user);
            this.submitted = true;
            this.v$.$touch();
            if (this.v$.$invalid) {
                return false;
            }
            alert('Validacion pasada');
        }
    }

}
</script>

// MASTER-FRAMEWORKD-JS/AprendiendoAngular/src/app/components/formulario/formulario.component.ts
import { Component,OnInit } from '@angular/core';

@Component({
  selector: 'app-formulario',
  standalone: false,
  templateUrl: './formulario.component.html',
  styleUrl: './formulario.component.css'
})
export class FormularioComponent implements OnInit {

  public user: any;
  public campo: string;

  constructor(){
    this.user={
      nombre: '',
      apellidos: '',
      bio: '',
      genero: ''
    };
    this.campo='';
  };

  ngOnInit(): void {
    
  }

  onSubmit(): void{
    alert('formulado enviado!!');
    console.log(this.user);
  }

  hasDadoClick(): void{
    alert('has dado click!!');
  }

  hasSalido(): void{
    alert('has salido!!');
  }
}

<app-slider 
            [nombre]="'Formulario'"
            [size]="'small'"
></app-slider>

<div class="center">
    
    <section id="content">
        <h1 class="subheader">Formulario</h1>
        <!--div id="datos-al-vuelo" *ngIf="user.nombre">
            <h2 class="subheader">Datos al vuelo</h2>
            <ul>
                <li>
                    {{user.nombre}}
                </li>
                <li>
                    {{user.apellidos}}
                </li>
                <li>
                    {{user.bio}}
                </li>
                <li>
                    {{user.genero}}
                </li>
            </ul>
        </div-->
        
        <form class="mid-form" #userForm="ngForm" (ngSubmit)="onSubmit()">
            <div class="form-group">
                <label for="nombre">Nombre</label>
                <input type="text" name="nombre" #nombre="ngModel" [(ngModel)]="user.nombre" 
                required pattern="[a-zA-Z]+"/>
                <small *ngIf="!nombre.valid && nombre.touched">
                    El nombre no es valido
                </small>
            </div>
            <div class="form-group">
                <label for="apellidos">Apellidos</label>
                <input type="text" name="apellidos" #apellidos="ngModel" [(ngModel)]="user.apellidos" required/>
                <small *ngIf="!apellidos.valid && apellidos.touched">
                    Los apellidos no es valido
                </small>
            </div>
            <div class="form-group">
                <label for="bio">Biografia</label>
                <textarea name="bio" #bio="ngModel" [(ngModel)]="user.bio" required></textarea>
                <small *ngIf="!bio.valid && bio.touched">
                    La biografia no es valido
                </small>
            </div>
            <div class="form-group radibuttons">
                <input type="radio" name="genero" value="hombre" #genero="ngModel"  [(ngModel)]="user.genero" required/> Hombre
                <input type="radio" name="genero" value="mujer" #genero="ngModel" [(ngModel)]="user.genero"/> Mujer
                <input type="radio" name="genero" value="otro" #genero="ngModel" [(ngModel)]="user.genero"/> Otro
                <small *ngIf="!genero.valid && genero.touched">
                    El genero no es valido
                </small>
            </div>
            <div class="clearfix"></div>
            <input type="submit" value="Enviar" class="btn btn-success" [disabled]="userForm.invalid"/>
        </form>

        <!--h2 class="subheader">Eventos</h2>
        <button (click)="hasDadoClick()">Darle click</button>
        <input type="text" [(ngModel)]="campo" (blur)="hasSalido()"/>
        <input type="text" [(ngModel)]="campo" (keyup.enter)="hasSalido()"/>
        {{campo}}-->
    </section>

    <app-sidebar></app-sidebar>
</div>
