// MASTER-FRAMEWORKD-JS/AprendiendoAngular/src/app/components/articles/articles.component.ts
import { Component,OnInit,Input } from '@angular/core';
import { Article } from '../../models/article';
import { Global } from '../../services/global';


@Component({
  selector: 'app-articles',
  standalone: false,
  templateUrl: './articles.component.html',
  styleUrl: './articles.component.css'
})
export class ArticlesComponent implements OnInit {

  @Input() articles?:Article[];
  public url: string;

  constructor(){
    this.url=Global.url;
  }

  ngOnInit(): void {
    console.log(this.articles);
  }
  
}

<div class="loading" *ngIf="!articles">
    Cargando...
</div>

<div class="loading" *ngIf="articles && articles.length == 0">
    No hay articulos para mostrar, intentalo mas tarde :)
</div>

<div id="articles" *ngFor="let article of articles">
    <article class="article-item" id="article-template">
        <div class="images-wrap">
            <img src="{{url+'get-image/'+article.image}}" alt="{{article.title}}" *ngIf="article.image" />
            <img src="https://image.shutterstock.com/z/stock-vector-image-icon-211642900.jpg" alt="{{article.title}}" *ngIf="!article.image" />
        </div>

        <h2>{{article.title}}</h2>
        <span class="date">
            {{article.date | date:'mediumDate'}}
        </span>
        <a [routerLink]="['/blog/articulo',article._id]">Leer mas</a>
        <div class="clearfix"></div>
    </article>
    
</div>

// MASTER-FRAMEWORKD-JS/aprendiendo-vue/src/components/ArticlesComponent.vue
<template>
    <section>
        <div id="articles-list" v-if="articles && articles.length >=1">
            <article class="article-item" v-for="article in articles" :key="article._id">
                <div class="images-wrap">
                    <img   
                        :src="url+'get-image/'+article.image"  
                        alt="article.title" 
                        v-if="article.image"
                    />
                    <img   
                        src="../assets/image/default.png"  
                        alt="article.title" 
                        v-if="!article.image"
                    />
                </div>
               
                <h2> 
                    <router-link :to="{name:'article',params:{id:article._id}}">                        
                        {{article.title}} 
                    </router-link>
                </h2>
               
                <span class="date">
                    {{ convertMoment(article.date) }}
                </span>
                <router-link :to="{name:'article',params:{id:article._id}}">                        
                        Leer mas
                </router-link>
                <div class="clearfix"></div>
            </article>
        </div>
        <div v-else-if="articles && articles.length < 1">
            No hay articulos para mostrar
        </div>
        <div v-else>
            Cargando....
        </div>
    </section>
</template>

<script>
import Global from '../Global';
import moment from 'moment';

export default {
    name: 'BlogComponent',
    props: ['articles'],
    data(){
        return {
            url:Global.url
        }
    },
    methods:{
        convertMoment(date){
            return moment(date).format("ll");
        }
    }
}

</script>
