// MASTER-FRAMEWORKD-JS/AprendiendoAngular/src/app/components/article/article.component.ts
import { Component,OnInit } from '@angular/core';
import { ArticleService } from '../../services/article.service';
import { Article } from '../../models/article';
import { Router, Params, ActivatedRoute } from '@angular/router';
import { Global } from '../../services/global';
import swal from 'sweetalert';

@Component({
  selector: 'app-article',
  standalone: false,
  templateUrl: './article.component.html',
  styleUrl: './article.component.css',
  providers: [ArticleService]
})
export class ArticleComponent implements OnInit {

  public article:Article;
  public url:string;

  constructor(
    private _articleService: ArticleService,
    private _route: ActivatedRoute,
    private _router: Router
  ){
    this.article={title:'','image':'','_id':'','content':'','date':''}
    this.url=Global.url;
  }

  ngOnInit(): void {
    this._route.params.subscribe(params =>{
      let id = params['id'];
      this._articleService.getArticle(id).subscribe(
        response =>{
          if (response.article) {
              this.article = response.article;
          }else{
              this._router.navigate(['/home']);
          }
        },
        error => {
          console.log(error);
          this._router.navigate(['/home']);
        }
      );
    })
  }
  delete(id:any){
    swal({
      title: "Estas seguro?",
      text: "Una vez borrado el articulo, no podras recuperarlo!",
      icon: "warning",
      buttons: ['Cancel', 'OK'],
      dangerMode: true
    })
    .then((willDelete) => {
      if (willDelete) {
        this._articleService.delete(id).subscribe(
          response=>{
            swal("El articulo ha sido borrado!!", {
              icon: "success",
            });
            this._router.navigate(['/blog']);
          },
          error =>{
            console.log(error);
            this._router.navigate(['/blog'])
          }
        );

      } else {
        swal("Tranquilo, nada se ha borrado!");
      }
    });
    
  }
}

<div class="center">
    
    <section id="content">
    
        <article class="article-item article-details">
            <div class="images-wrap">
                <img src="{{url+'get-image/'+article.image}}" alt="{{article.title}}" *ngIf="article.image" />
                <img src="https://image.shutterstock.com/z/stock-vector-image-icon-211642900.jpg" alt="{{article.title}}" *ngIf="!article.image" />
            </div>

            <h1 class="subheader">{{article.title}}</h1>
            <span class="date">
                {{article.date | date:'mediumDate'}}
            </span>
            <p>
                {{article.content}}
            </p>
            <div class="buttons">
                <a [routerLink]="['/blog/editar', article._id]" class="btn btn-warning">Editar</a>
                <a (click)="delete(article._id)" class="btn btn-danger">Borrar</a>
            </div>
            <div class="clearfix"></div>
        </article>
    
    </section>

    <app-sidebar></app-sidebar>
</div>

// MASTER-FRAMEWORKD-JS/aprendiendo-vue/src/components/ArticleComponent.vue
<template>
    <div class="general">
        <div class="center">
            <section id="content">
                <div id="articles">
                    <article class="article-item article-details" v-if="article">
                        <div class="images-wrap">
                            <img 
                                :src="url+'get-image/'+article.image"
                                :alt="article.title" 
                                v-if="article.image"
                            />
                            <img src="../assets/image/default.png"  :alt="article.title" 
                                v-else/>
                        </div>

                        <h1 class="subheader">{{ article.title }}</h1>
                        <span class="date">
                            {{ convertMoment(article.date) }}
                        </span>
                        <p>
                            {{article.content}}
                        </p>
                        <div class="clearfix"></div>
                        <router-link :to="'/editar/'+article._id" class="btn btn-warning">Editar</router-link>
                        <a @click="deleteArticle(article._id)" class="btn btn-danger">Eliminar</a>
                    </article>

                </div>
            </section>
        </div>
        <SiderbarComponent></SiderbarComponent>
        <div class="clearfix"></div>
    </div>
</template>

<script>
import SiderbarComponent from './SiderbarComponent.vue';
import Global from '../Global';
import axios from 'axios';
import moment from 'moment';
import swal from 'sweetalert';

export default {
    name: 'ArticleComponent',
    components:{
        SiderbarComponent
    },
    data(){
        return {
            url: Global.url,
            article: null
        }
    },
    mounted(){
        var articleId= this.$route.params.id;
        this.getArticle(articleId);
    },
    methods:{
        getArticle(articleId){
            axios.get(this.url+'article/'+articleId).then( res =>{
                if (res.data.status === 'success') {
                    this.article = res.data.article;
                }
            });
        },
        convertMoment(date){
            return moment(date).format("ll");
        },
        deleteArticle(articleId){
            swal({
                title: "Estas seguro?",
                text: "Borrarás permanentemente tu articulo",
                icon: "warning",
                buttons: true,
                dangerMode: true,
                })
                .then((willDelete) => {
                    if (willDelete) {
                        axios.delete(this.url+'article/'+articleId)
                        .then(res => {
                            if(res.data.status=='success'){
                                swal(
                                    'Articulo borrado',
                                    'El articulo ha sido borrado correctamente',
                                    'success'
                                );  
                                this.$router.push('/blog');  
                            }  
                        });
                    } else {
                        swal(
                            'Tranquilo',
                            'No se ha borrado nada',
                            'info'
                        );
                    }
            });
        }
    }

}
</script>
